version: '3'
services:
  espresso-brew-tracker:
    build: .
    ports:
      - "3000:3000"   # Frontend
      - "4000:4000"   # API
    volumes:
      - ./server:/app/server
    restart: unless-stopped
